Bnb/mirror_padding
NREL/phygnn pull request #28
Opened 2022-01-11 21:49 UTC by bnb32

added ReflectionPadding class to custom_layers.py. issue #27

2022-01-12 16:31 UTC, grantbuster commented
Looks good! Can you just add a test then we'll merge?

2022-01-12 16:31 UTC, grantbuster commented
Not sure whats up with the tf1.15 test. I can take care of that later.

2022-01-12 21:37 UTC, bnb32 commented
yeah it looks like a file for that test was removed during the refactoring

2022-01-19 16:00 UTC, grantbuster requested changes
A few changes, mostly on the test methods. also, in `.github/workflows/pull_request_tests_tf_1_15.yml` can you try changing `python -m pytest ./tests/test_tf_layers.py -v` to ->> `python -m pytest ./tests/test_layers.py -v` ? I think this is the only reason that the pytests are failing.

2022-01-19 16:20 UTC, bnb32 commented on tests/test_layers.py
> +def test_padding_layers():
Yeah I was unsure how exactly to "integrate with hiddenlayers". This makes sense.

2022-01-19 16:21 UTC, bnb32 commented on tests/test_layers.py
> +                     [4, 5, 6]])
Sounds good!

2022-01-19 16:23 UTC, grantbuster commented on tests/test_layers.py
> +def test_padding_layers():
I should have explained this better, basically the `HiddenLayers` class is a handler that takes a config-style set of arguments to make an ordered list of network layers. You can retrieve any of the custom layer classes by setting `'class': CustomClass`. There's more detail in the `HiddenLayers` docstrings too.

2022-01-19 16:30 UTC, bnb32 commented on phygnn/layers/custom_layers.py
> +        return tf.pad(x, tf.constant(self.paddings),
good point

2022-01-19 16:40 UTC, bnb32 commented on tests/test_layers.py
> +def test_padding_layers():
Yeah the example helped. Thanks!

2022-01-19 21:49 UTC, grantbuster approved these changes

2022-01-19 23:09 UTC, merged